id: I7C774495
source: https://www.lotsawahouse.org
source_file: null
initial_creation_type: input
imported: '2022-06-17T12:21:11.747537'
last_modified: '2022-06-17T12:21:11.747558'
parser: null
source_metadata:
  title: Kṣitigarbha Series
  language: bo
  description: 'Texts related to Kṣitigarbha (sa’i snying po), one of the eight great
    bodhisattvas:'
  volume:
    f9828:
      title: 'Beautiful Adornment of the Earth: In Praise of Kṣitigarbha'
      base_file: f9828.txt
      order: 1
      parent: Praise
    fEEA7:
      title: Kṣitigarbha Visualization and Mantra Recitation
      base_file: fEEA7.txt
      order: 2
      parent: Sādhanas
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
